theme: jekyll-theme-cayman
title: Bienvenido a comunidad Maker de Mallorca
description: Sabemos que el espíritu Maker está presente en Mallorca. Y queremos reunir a todos aquellos que disfruten del ´háztelo tu mismo´ usando nuevas tecnologías digitales e industriales
